In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)
pd.set_option("display.float_format", "{:,.2f}".format)

In [2]:
customers = pd.read_csv("../data/raw/customers.csv")
products = pd.read_csv("../data/raw/products.csv")
stores = pd.read_csv("../data/raw/stores.csv")
delivery_partners = pd.read_csv("../data/raw/delivery_partners.csv")
orders = pd.read_csv("../data/raw/orders.csv")
order_items = pd.read_csv("../data/raw/order_items.csv")
payments = pd.read_csv("../data/raw/payments.csv")
coupons = pd.read_csv("../data/raw/coupons.csv")
calendar = pd.read_csv("../data/raw/calendar.csv")

In [3]:
datasets = {
    "Customers": customers,
    "Products": products,
    "Stores": stores,
    "Delivery Partners": delivery_partners,
    "Orders": orders,
    "Order Items": order_items,
    "Payments": payments,
    "Coupons": coupons,
    "Calendar": calendar
}

In [4]:
def dataset_overview(df, name):

    print("="*80)
    print(name.upper())
    print("="*80)

    print(f"Rows : {df.shape[0]:,}")
    print(f"Columns : {df.shape[1]}")

    print("\nData Types")
    print(df.dtypes)

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicate Rows")
    print(df.duplicated().sum())

    print("\nMemory Usage")
    print(f"{df.memory_usage(deep=True).sum()/1024**2:.2f} MB")

    print("\nFirst Five Rows")
    display(df.head())

In [5]:
for name, df in datasets.items():
    dataset_overview(df, name)

================================================================================
CUSTOMERS
================================================================================
Rows : 250,000
Columns : 8

Data Types
customer_id             int64
signup_date            object
gender                 object
age                     int64
city                   object
membership_type        object
acquisition_channel    object
customer_status        object
dtype: object

Missing Values
customer_id            0
signup_date            0
gender                 0
age                    0
city                   0
membership_type        0
acquisition_channel    0
customer_status        0
dtype: int64

Duplicate Rows
0

Memory Usage
83.99 MB

First Five Rows

,customer_id,signup_date,gender,age,city,membership_type,acquisition_channel,customer_status
0,1,2025-09-26,Female,58,Hyderabad,Normal,Google Ads,Active
1,2,2024-12-28,Male,25,Delhi,Plus,Instagram,Active
2,3,2025-07-04,Female,23,Bangalore,Normal,Google Ads,Active
3,4,2025-07-20,Male,33,Delhi,Normal,Instagram,Active
4,5,2026-06-06,Male,29,Mumbai,Normal,Instagram,Active

================================================================================
PRODUCTS
================================================================================
Rows : 8,000
Columns : 15

Data Types
product_id             int64
SKU                   object
product_name          object
brand                 object
category              object
subcategory           object
MRP                  float64
selling_price        float64
cost_price           float64
weight                object
supplier              object
GST_rate             float64
rating               float64
launch_date           object
discontinued_flag      int64
dtype: object

Missing Values
product_id           0
SKU                  0
product_name         0
brand                0
category             0
subcategory          0
MRP                  0
selling_price        0
cost_price           0
weight               0
supplier             0
GST_rate             0
rating               0
launch_date          0
discontinued_flag    0
dtype: int64

Duplicate Rows
0

Memory Usage
4.12 MB

First Five Rows

,product_id,SKU,product_name,brand,category,subcategory,MRP,selling_price,cost_price,weight,supplier,GST_rate,rating,launch_date,discontinued_flag
0,1,SKU-52068,Coca Cola Coke 500ml 0,Coca Cola,Beverages,Beverages Sub,"1,172.58",944.54,705.86,100g,Coca Cola,0.05,4.00,2022-01-01,0
1,2,SKU-41352,Aashirvaad Atta 5kg 1,Aashirvaad,Staples & Kitchen,Staples & Kitchen Sub,393.83,353.35,264.48,1L,Aashirvaad,0.12,4.60,2022-01-01,0
2,3,SKU-64262,Dettol Antiseptic 2,Dettol,Cleaning,Cleaning Sub,"1,161.55","1,013.77",831.83,100g,Dettol,0.05,3.50,2022-01-01,0
3,4,SKU-66124,Cadbury Dairy Milk Silk 3,Cadbury,Snacks & Munchies,Snacks & Munchies Sub,"1,216.62","1,149.52",776.58,1kg,Cadbury,0.12,3.70,2022-01-01,0
4,5,SKU-65305,Fortune Sunflower Oil 1L 4,Fortune,Staples & Kitchen,Staples & Kitchen Sub,959.68,894.02,588.82,500g,Fortune,0.12,4.60,2022-01-01,0

================================================================================
STORES
================================================================================
Rows : 120
Columns : 5

Data Types
store_id               int64
city                  object
locality              object
opening_date          object
warehouse_capacity     int64
dtype: object

Missing Values
store_id              0
city                  0
locality              0
opening_date          0
warehouse_capacity    0
dtype: int64

Duplicate Rows
0

Memory Usage
0.02 MB

First Five Rows

   store_id       city      locality opening_date  warehouse_capacity
0         1  Bangalore  Dark Store 0   2022-01-01                5000
1         2    Gurgaon  Dark Store 1   2022-01-01               10000
2         3     Mumbai  Dark Store 2   2022-01-01                5000
3         4    Gurgaon  Dark Store 3   2022-01-01               10000
4         5    Gurgaon  Dark Store 4   2022-01-01                5000

================================================================================
DELIVERY PARTNERS
================================================================================
Rows : 15,000
Columns : 6

Data Types
delivery_partner_id      int64
joining_date            object
city                    object
vehicle_type            object
employment_type         object
average_rating         float64
dtype: object

Missing Values
delivery_partner_id    0
joining_date           0
city                   0
vehicle_type           0
employment_type        0
average_rating         0
dtype: int64

Duplicate Rows
0

Memory Usage
3.38 MB

First Five Rows

,delivery_partner_id,joining_date,city,vehicle_type,employment_type,average_rating
0,1,2026-03-28,Gurgaon,Scooter,Gig,4.50
1,2,2025-09-02,Delhi,EV,Gig,4.90
2,3,2025-10-05,Bangalore,Scooter,Gig,4.90
3,4,2026-02-15,Delhi,Scooter,Gig,4.80
4,5,2025-10-17,Hyderabad,Bike,Gig,4.30

================================================================================
ORDERS
================================================================================
Rows : 1,000,000
Columns : 26

Data Types
order_id                 int64
customer_id              int64
store_id                 int64
delivery_partner_id      int64
payment_id               int64
                        ...
total_paid             float64
tip_amount               int64
customer_rating        float64
sla_met                 object
order_source            object
Length: 26, dtype: object

Missing Values
order_id                   0
customer_id                0
store_id                   0
delivery_partner_id        0
payment_id                 0
                       ...
total_paid                 0
tip_amount                 0
customer_rating        60041
sla_met                    0
order_source               0
Length: 26, dtype: int64

Duplicate Rows
0

Memory Usage
602.42 MB

First Five Rows

,order_id,customer_id,store_id,delivery_partner_id,payment_id,coupon_id,order_datetime,delivery_datetime,promised_delivery_minutes,actual_delivery_minutes,delivery_distance_km,order_status,cancellation_reason,weather,traffic_level,payment_method,order_value,delivery_fee,platform_fee,packaging_fee,discount,total_paid,tip_amount,customer_rating,sla_met,order_source
0,1,142094,72,11611,1,191,2023-01-28 20:32:00,2023-01-28 21:02:00,35,30.00,4.13,Delivered,NaN,Clear,Low,Online,"5,884.89",25,2,5,882.73,"5,034.16",0,4.90,No,Android
1,2,89101,101,5329,2,248,2023-05-25 20:55:00,2023-05-25 21:33:00,35,38.00,3.75,Delivered,NaN,Clear,High,Online,"5,235.77",25,2,5,785.37,"4,482.40",0,4.50,No,Android
2,3,116801,120,11346,3,18,2023-05-22 21:07:00,2023-05-22 21:45:00,35,38.00,5.81,Delivered,NaN,Clear,Medium,Online,"1,987.32",25,2,5,298.10,"1,721.22",0,4.70,No,Android
3,4,204959,61,7532,4,220,2023-04-24 10:36:00,2023-04-24 10:52:00,25,16.00,1.66,Delivered,NaN,Clear,Low,Online,"6,062.99",25,2,5,909.45,"5,185.54",0,5.00,Yes,Android
4,5,15915,75,5313,5,182,2023-04-26 16:26:00,2023-04-26 16:54:00,25,28.00,1.61,Delivered,NaN,Clear,High,Online,"1,973.18",25,2,5,295.98,"1,719.20",10,3.50,No,Android

================================================================================
ORDER ITEMS
================================================================================
Rows : 5,498,786
Columns : 8

Data Types
order_item_id           int64
order_id                int64
product_id              int64
quantity                int64
unit_price            float64
item_discount           int64
total_price           float64
cost_price_at_sale    float64
dtype: object

Missing Values
order_item_id         0
order_id              0
product_id            0
quantity              0
unit_price            0
item_discount         0
total_price           0
cost_price_at_sale    0
dtype: int64

Duplicate Rows
0

Memory Usage
335.62 MB

First Five Rows

,order_item_id,order_id,product_id,quantity,unit_price,item_discount,total_price,cost_price_at_sale
0,1,1,836,2,999.01,0,"1,998.02","1,486.70"
1,2,1,7643,1,115.23,0,115.23,78.48
2,3,1,5578,1,"1,337.40",0,"1,337.40",883.76
3,4,1,1416,1,183.60,0,183.60,138.22
4,5,1,2520,2,"1,125.32",0,"2,250.64","1,578.88"

================================================================================
PAYMENTS
================================================================================
Rows : 1,000,000
Columns : 7

Data Types
payment_id               int64
payment_method          object
payment_status          object
gateway                 object
payment_time_seconds     int64
cashback                 int64
refund_amount            int64
dtype: object

Missing Values
payment_id              0
payment_method          0
payment_status          0
gateway                 0
payment_time_seconds    0
cashback                0
refund_amount           0
dtype: int64

Duplicate Rows
0

Memory Usage
188.22 MB

First Five Rows

,payment_id,payment_method,payment_status,gateway,payment_time_seconds,cashback,refund_amount
0,1,Card,Success,Razorpay,15,0,0
1,2,Card,Success,Razorpay,15,0,0
2,3,Card,Success,Razorpay,15,0,0
3,4,Card,Success,Razorpay,15,0,0
4,5,UPI,Success,Razorpay,15,0,0

================================================================================
COUPONS
================================================================================
Rows : 250
Columns : 5

Data Types
coupon_id            int64
coupon_code         object
discount_type       object
minimum_order        int64
maximum_discount     int64
dtype: object

Missing Values
coupon_id           0
coupon_code         0
discount_type       0
minimum_order       0
maximum_discount    0
dtype: int64

Duplicate Rows
0

Memory Usage
0.03 MB

First Five Rows

   coupon_id coupon_code discount_type  minimum_order  maximum_discount
0          1      SAVE10    Percentage            299               100
1          2      SAVE11    Percentage            299               100
2          3      SAVE12    Percentage            299               100
3          4      SAVE13    Percentage            299               100
4          5      SAVE14    Percentage            299               100

================================================================================
CALENDAR
================================================================================
Rows : 365
Columns : 9

Data Types
date           object
day_name       object
week_number     int64
month           int64
quarter         int64
year            int64
is_weekend      int64
festival       object
is_holiday      int64
dtype: object

Missing Values
date             0
day_name         0
week_number      0
month            0
quarter          0
year             0
is_weekend       0
festival       358
is_holiday       0
dtype: int64

Duplicate Rows
0

Memory Usage
0.07 MB

First Five Rows

,date,day_name,week_number,month,quarter,year,is_weekend,festival,is_holiday
0,2023-01-01,Sunday,52,1,1,2023,1,NaN,1
1,2023-01-02,Monday,1,1,1,2023,0,NaN,0
2,2023-01-03,Tuesday,1,1,1,2023,0,NaN,0
3,2023-01-04,Wednesday,1,1,1,2023,0,NaN,0
4,2023-01-05,Thursday,1,1,1,2023,0,NaN,0

In [6]:
quality_report = []

for name, df in datasets.items():

    quality_report.append({

        "Table": name,

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Missing Values": df.isnull().sum().sum(),

        "Duplicate Rows": df.duplicated().sum(),

        "Memory (MB)": round(df.memory_usage(deep=True).sum()/1024**2,2)

    })

quality_report = pd.DataFrame(quality_report)

quality_report

,Table,Rows,Columns,Missing Values,Duplicate Rows,Memory (MB)
0,Customers,250000,8,0,0,83.99
1,Products,8000,15,0,0,4.12
2,Stores,120,5,0,0,0.02
3,Delivery Partners,15000,6,0,0,3.38
4,Orders,1000000,26,1120082,0,602.42
5,Order Items,5498786,8,0,0,335.62
6,Payments,1000000,7,0,0,188.22
7,Coupons,250,5,0,0,0.03
8,Calendar,365,9,358,0,0.07

In [7]:
print(customers.customer_id.is_unique)
print(products.product_id.is_unique)
print(stores.store_id.is_unique)
print(delivery_partners.delivery_partner_id.is_unique)
print(orders.order_id.is_unique)
print(order_items.order_item_id.is_unique)
print(payments.payment_id.is_unique)
print(coupons.coupon_id.is_unique)

True
True
True
True
True
True
True
True

In [8]:
print(orders.customer_id.isin(customers.customer_id).all())

print(orders.store_id.isin(stores.store_id).all())

print(orders.delivery_partner_id.isin(delivery_partners.delivery_partner_id).all())

print(orders.payment_id.isin(payments.payment_id).all())

print(orders.coupon_id.isin(coupons.coupon_id).all())

print(order_items.order_id.isin(orders.order_id).all())

print(order_items.product_id.isin(products.product_id).all())

True
True
True
True
True
True
True

In [9]:
(products["selling_price"] <= products["MRP"]).all()

np.True_

In [10]:
(products["cost_price"] <= products["selling_price"]).all()

np.True_

In [11]:
(
    orders["total_paid"].round(2)
    ==
    (
        orders["order_value"]
        - orders["discount"]
        + orders["delivery_fee"]
        + orders["platform_fee"]
        + orders["packaging_fee"]
        + orders["tip_amount"]
    ).round(2)
).all()

np.True_

In [12]:
mask = (
    orders["total_paid"] !=
    orders["order_value"]
    - orders["discount"]
    + orders["delivery_fee"]
    + orders["platform_fee"]
    + orders["packaging_fee"]
    + orders["tip_amount"]
)

orders.loc[
    mask,
    [
        "order_id",
        "order_value",
        "discount",
        "delivery_fee",
        "platform_fee",
        "packaging_fee",
        "tip_amount",
        "total_paid"
    ]
].head(10)

,order_id,order_value,discount,delivery_fee,platform_fee,packaging_fee,tip_amount,total_paid
1,2,"5,235.77",785.37,25,2,5,0,"4,482.40"
2,3,"1,987.32",298.10,25,2,5,0,"1,721.22"
5,6,"8,252.45","1,237.87",25,2,5,0,"7,046.58"
8,9,"5,757.14",863.57,25,2,5,10,"4,935.57"
10,11,"2,029.22",304.38,25,2,5,0,"1,756.84"
13,14,"9,070.03","1,360.50",25,2,5,0,"7,741.53"
26,27,"2,082.17",312.33,25,2,5,0,"1,801.84"
28,29,"5,404.73",810.71,25,2,5,0,"4,626.02"
33,34,"6,084.23",912.63,25,2,5,10,"5,213.60"
35,36,"3,930.62",589.59,25,2,5,0,"3,373.03"

In [13]:
mask.sum()

np.int64(66858)

In [14]:
orders["order_datetime"] = pd.to_datetime(orders["order_datetime"])
orders["delivery_datetime"] = pd.to_datetime(orders["delivery_datetime"])

customers["signup_date"] = pd.to_datetime(customers["signup_date"])

calendar["date"] = pd.to_datetime(calendar["date"])

In [15]:
orders["order_hour"] = orders["order_datetime"].dt.hour

In [16]:
orders["day_name"] = orders["order_datetime"].dt.day_name()

In [17]:
orders["month"] = orders["order_datetime"].dt.month_name()

In [18]:
orders["is_weekend"] = orders["day_name"].isin(
    ["Saturday", "Sunday"]
)

In [19]:
orders["delivery_status_category"] = np.where(
    orders["order_status"] == "Cancelled",
    "Cancelled",
    np.where(
        orders["actual_delivery_minutes"]
        <=
        orders["promised_delivery_minutes"],
        "On-Time",
        "Delayed"
    )
)

In [20]:
order_items = order_items.merge(
    products[["product_id","cost_price"]],
    on="product_id",
    how="left"
)

order_items["profit"] = (
    order_items["unit_price"]
    - order_items["cost_price"]
) * order_items["quantity"]

In [21]:
order_items["profit_margin"] = (
    order_items["profit"]
    /
    order_items["total_price"]
) * 100

In [22]:
datasets["Order Items"] = order_items

In [23]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.isnull().sum())

Customers
customer_id            0
signup_date            0
gender                 0
age                    0
city                   0
membership_type        0
acquisition_channel    0
customer_status        0
dtype: int64

Products
product_id           0
SKU                  0
product_name         0
brand                0
category             0
subcategory          0
MRP                  0
selling_price        0
cost_price           0
weight               0
supplier             0
GST_rate             0
rating               0
launch_date          0
discontinued_flag    0
dtype: int64

Stores
store_id              0
city                  0
locality              0
opening_date          0
warehouse_capacity    0
dtype: int64

Delivery Partners
delivery_partner_id    0
joining_date           0
city                   0
vehicle_type           0
employment_type        0
average_rating         0
dtype: int64

Orders
order_id                    0
customer_id                 0
store_id                    0
delivery_partner_id         0
payment_id                  0
                           ..
order_hour                  0
day_name                    0
month                       0
is_weekend                  0
delivery_status_category    0
Length: 31, dtype: int64

Order Items
order_item_id         0
order_id              0
product_id            0
quantity              0
unit_price            0
item_discount         0
total_price           0
cost_price_at_sale    0
cost_price            0
profit                0
profit_margin         0
dtype: int64

Payments
payment_id              0
payment_method          0
payment_status          0
gateway                 0
payment_time_seconds    0
cashback                0
refund_amount           0
dtype: int64

Coupons
coupon_id           0
coupon_code         0
discount_type       0
minimum_order       0
maximum_discount    0
dtype: int64

Calendar
date             0
day_name         0
week_number      0
month            0
quarter          0
year             0
is_weekend       0
festival       358
is_holiday       0
dtype: int64

In [24]:
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()}")

Customers: 0
Products: 0
Stores: 0
Delivery Partners: 0
Orders: 0
Order Items: 0
Payments: 0
Coupons: 0
Calendar: 0

In [25]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.dtypes)

Customers
customer_id                     int64
signup_date            datetime64[ns]
gender                         object
age                             int64
city                           object
membership_type                object
acquisition_channel            object
customer_status                object
dtype: object

Products
product_id             int64
SKU                   object
product_name          object
brand                 object
category              object
subcategory           object
MRP                  float64
selling_price        float64
cost_price           float64
weight                object
supplier              object
GST_rate             float64
rating               float64
launch_date           object
discontinued_flag      int64
dtype: object

Stores
store_id               int64
city                  object
locality              object
opening_date          object
warehouse_capacity     int64
dtype: object

Delivery Partners
delivery_partner_id      int64
joining_date            object
city                    object
vehicle_type            object
employment_type         object
average_rating         float64
dtype: object

Orders
order_id                     int64
customer_id                  int64
store_id                     int64
delivery_partner_id          int64
payment_id                   int64
                             ...
order_hour                   int32
day_name                    object
month                       object
is_weekend                    bool
delivery_status_category    object
Length: 31, dtype: object

Order Items
order_item_id           int64
order_id                int64
product_id              int64
quantity                int64
unit_price            float64
item_discount           int64
total_price           float64
cost_price_at_sale    float64
cost_price            float64
profit                float64
profit_margin         float64
dtype: object

Payments
payment_id               int64
payment_method          object
payment_status          object
gateway                 object
payment_time_seconds     int64
cashback                 int64
refund_amount            int64
dtype: object

Coupons
coupon_id            int64
coupon_code         object
discount_type       object
minimum_order        int64
maximum_discount     int64
dtype: object

Calendar
date           datetime64[ns]
day_name               object
week_number             int64
month                   int64
quarter                 int64
year                    int64
is_weekend              int64
festival               object
is_holiday              int64
dtype: object

In [26]:
orders["order_value"].describe()

count   1,000,000.00
mean        4,346.05
std         2,578.55
min            16.81
25%         2,206.76
50%         4,170.68
75%         6,234.63
max        15,776.77
Name: order_value, dtype: float64

In [27]:
orders["actual_delivery_minutes"].describe()

count   939,959.00
mean         30.20
std           9.10
min          12.00
25%          23.00
50%          30.00
75%          36.00
max          64.00
Name: actual_delivery_minutes, dtype: float64

In [28]:
orders["delivery_distance_km"].describe()

count   1,000,000.00
mean            3.25
std             1.59
min             0.50
25%             1.87
50%             3.25
75%             4.62
max             6.00
Name: delivery_distance_km, dtype: float64

In [29]:
products[["MRP","selling_price","cost_price"]].describe()

           MRP  selling_price  cost_price
count 8,000.00       8,000.00    8,000.00
mean    771.67         686.78      515.57
std     428.10         383.93      292.13
min      20.28          16.81       11.04
25%     400.42         355.38      265.96
50%     785.13         693.38      516.62
75%   1,146.76       1,012.91      760.10
max   1,499.92       1,464.62    1,209.85

In [30]:
from pathlib import Path

# Create cleaned folder if it doesn't exist
Path("../data/cleaned").mkdir(parents=True, exist_ok=True)

# Save cleaned datasets
customers.to_csv("../data/cleaned/customers.csv", index=False)
products.to_csv("../data/cleaned/products.csv", index=False)
stores.to_csv("../data/cleaned/stores.csv", index=False)
delivery_partners.to_csv("../data/cleaned/delivery_partners.csv", index=False)
orders.to_csv("../data/cleaned/orders.csv", index=False)
order_items.to_csv("../data/cleaned/order_items.csv", index=False)
payments.to_csv("../data/cleaned/payments.csv", index=False)
coupons.to_csv("../data/cleaned/coupons.csv", index=False)
calendar.to_csv("../data/cleaned/calendar.csv", index=False)

print("✅ Cleaned datasets exported successfully!")

✅ Cleaned datasets exported successfully!